name: Notify Slack on new actor events

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
  discussion:
    types: [created]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch list of contributors
        id: fetch_contributors
        uses: actions/github-script@v6
        with:
          script: |
            const contributors = await github.paginate(github.repos.listContributors, {
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            return contributors.map(contributor => contributor.login);

      - name: Check if actor is new
        id: check_actor
        run: |
          echo "actor_is_new=false" >> $GITHUB_ENV
          if [[ ! " ${contributors[*]} " =~ " ${GITHUB_ACTOR} " ]]; then
            echo "actor_is_new=true" >> $GITHUB_ENV
          fi

      - name: Send notification to Slack
        if: env.actor_is_new == 'true'
        uses: slackapi/slack-github-action@v1.23.0
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          slack-message: |
            A new event has occurred in the repository.
            Event type: ${{ github.event_name }}
            Actor: ${{ github.actor }}
            Link: ${{ github.event.html_url }}
            This is an interaction from a new contributor. Please respond ASAP.
