# Server configuration
server.port=8080

# Endpoints
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true

# Benchmark configuration
benchmark.key-space-size=500000
benchmark.get-existing-ratio=0.8
benchmark.get-nonexisting-set-ratio=0.2

# Valkey/Redis server configuration
# Valkey endpoint
benchmark.valkey.host=clustercfg.testingprimevalkey.ey5v7d.use2.cache.amazonaws.com
benchmark.valkey.port=6379
benchmark.valkey.use-tls=true

# Redis endpoint
benchmark.redis.host=clustercfg.primetestinredis.ey5v7d.use2.cache.amazonaws.com
benchmark.redis.port=6379
benchmark.redis.use-tls=true

# Glide client configuration
benchmark.glide.client-az=us-east-2b
benchmark.glide.read-from=AZ_AFFINITY

# Redisson client configuration
benchmark.redisson.connection-timeout=10000
benchmark.redisson.timeout=1000
benchmark.redisson.idle-connection-timeout=1000
benchmark.redisson.master-connections-min-idle-size=10
benchmark.redisson.master-connections-pool-size=24
benchmark.redisson.slave-connections-min-idle-size=10
benchmark.redisson.slave-connections-pool-size=24
benchmark.redisson.retry-attempts=3
benchmark.redisson.retry-interval=1000

# Value size configuration (in characters)
benchmark.value.paragraph-min-size=200
benchmark.value.paragraph-max-size=800

# Logging
logging.level.root=INFO
logging.level.glide.benchmark=INFO
logging.level.org.redisson=WARN
